"""Valor Produto | Quantidade

Revision ID: 6bd4698820a8
Revises: bf81190abfdf
Create Date: 2022-12-29 01:35:16.104512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd4698820a8'
down_revision = 'bf81190abfdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Produto', sa.Column('valor_produto', sa.Integer(), nullable=True))
    op.add_column('Produto', sa.Column('quantidade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Produto', 'quantidade')
    op.drop_column('Produto', 'valor_produto')
    # ### end Alembic commands ###
